### ISSUE TITLE
Demo site is down

### ISSUE THREAD

**Issue by Nipodemos** [webpro/dyson#107]
Hello!
I went to see the demo of your package working but it seems is not working: https://dyson-demo-npzwhgjdor.now.sh/

**Comment by webpro** [comment]
Thanks @Nipodemos! Didn't realize this. It's now at https://dyson-demo.herokuapp.com

**Comment by Nipodemos** [comment]
you're welcome!
by  the way, is there a place were i can get some help with this package?
i know the issue is not the place for ask question, so i wanted to know if there is a community for this package

**Comment by webpro** [comment]
Personally, I think issues here are fine to ask questions! We can label them with "question" and it might be useful for other people as well. Otherwise feel free to drop me a line on Twitter (https://twitter.com/webprolific) or by email (lars@webpro.nl). To be honest, I don't think there's a community for this package. I'm happy to maintain dyson, I believe there's still plenty of users, but it's not under active development anymore.
